name: mpc/mp-core-form
label: MP Core - Form Extension Configuration
dependencies:
  - mpc/mp-core
optionalDependencies:
  - typo3/form
settings:
  definitions: settings.definitions.yaml
  defaults: settings.yaml

